repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - --line-length=100

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-yaml
        exclude: (config.*\.yml)$
      - id: debug-statements
      - id: check-case-conflict

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          - --max-line-length=100
          - --max-complexity=18
          - --ignore=E501,F401,W503,W605
          - --select=B,C,E,F,W,T4,B9

  # - repo: local
  #   hooks:
  #     - id: tests
  #       name: run unit tests
  #       entry: ./bin/manage test test
  #       language: system
  #       pass_filenames: false